version: "3.7"

networks:
  back-tier:
    driver: bridge

services:
  lore-api:
    image: dockerhub.northeurope.cloudapp.azure.com/lore-api:latest
    depends_on:
      - lore-db
    build:
      context: .
      dockerfile: src/Lore.Web/Dockerfile
    ports:
      - "8000:80"
      - "9000:443"
    restart: always
    environment:
      DB_CONNECTION_STRING: host=lore-db;port=5432;database=db-test;username=db-user;password=db-pass
    networks:
      - back-tier

  lore-db:
    image: postgres:latest
    hostname: lore-db
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "db-user"
      POSTGRES_PASSWORD: "db-pass"
      POSTGRES_DB: "db-test"
    networks:
      - back-tier

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - lore-db
    ports:
      - "5000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - back-tier
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.1.0
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    networks:
      - back-tier

  grafana:
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: always
    ports:
      - 3000:3000
    networks:
      - back-tier

volumes:
  db_volume: {}
  pgadmin: {}
  prometheus_data: {}
  grafana_data: {}
