version: "3.4"

networks:
  back-tier:
    driver: bridge

services:
  # lore-client:
  #   build:
  #     context: .
  #     dockerfile: src/Lore.Web/Client/Dockerfile
  #   image: dockerhub.northeurope.cloudapp.azure.com/lore-client:latest
  #   ports:
  #     - "8000:80"
  #     - "9000:443"
  #   networks:
  #     - back-tier
  #   depends_on:
  #     - lore-api

  lore-api:
    image: dockerhub.northeurope.cloudapp.azure.com/lore-api:latest
    depends_on:
      - lore-db
    ports:
      - "8000:80"
      - "9000:443"
    build:
      context: .
      dockerfile: src/Lore.Web/Dockerfile
    restart: always
    environment:
      DB_CONNECTION_STRING: host=lore-db;port=5432;database=db-test;username=db-user;password=db-pass
    networks:
      - back-tier

  lore-db:
    image: postgres:latest
    hostname: lore-db
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "db-user"
      POSTGRES_PASSWORD: "db-pass"
      POSTGRES_DB: "db-test"
    networks:
      - back-tier

volumes:
  db_volume: {}
  pgadmin: {}
  prometheus_data: {}
  grafana_data: {}
